version: "3.8"
services:
  vector:
    build:
      context: ./docker 
      args:
        log_group_name: "fakegroupname"
        config_file: "vector.development.toml"
    ports: 
      - "5002:5002"
  syslog_client:
    build: ./syslog_client
    ports:
      - "5000:5000"
