version: "3.8"
services:
  syslog_server:
    build:
      context: ./docker
      args:
        log_group_name: "fakegroupname"
        config_file: "fluent-bit.development.conf"
    ports:
      - "514:514"
  syslog_client:
    build: ./syslog_client
    ports:
      - "5000:5000"
