[sources.in]
  address = "0.0.0.0:514"
  type = "syslog"
  mode = "udp"

[sinks.production]
  # General
  type = "aws_cloudwatch_logs"
  inputs = ["in"]
  group_name = "<AWS_LOG_GROUP_NAME>"
  region = "eu-west-2"
  stream_name = "{{ host }}"
  max_events = 1

 # Encoding
  encoding.codec = "json"
